[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32H743BI --defmt"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "inline-threshold=225",
  #"-C", "debug-assertions=off",
]

[build]
target = "thumbv7em-none-eabihf"

[profile.release]
codegen-units = 1
opt-level = 3
debug = 2
lto = "fat"
incremental = false

[profile.dev.package."*"]
opt-level = "s"
